/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/white_double_windowed_door/scene.gltf -o app/assets/3dmodel/WhiteDoubleWindowedDoor.jsx 
Author: TastyShed (https://sketchfab.com/TastyFabs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/white-double-windowed-door-2d842a0f609245fb9bbe922669891ba4
Title: White Double Windowed Door
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function DoubleGlass(props) {
  const { nodes, materials } = useGLTF('/white_double_windowed_door/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.02}>
        <group position={[-81.831, 1220.264, 3.487]} rotation={[-Math.PI / 2, 0, 0]} scale={[5, 70, 137.5]}>
          <mesh geometry={nodes.SmallDoor_WhiteWalls001_0.geometry} material={materials['WhiteWalls.001']} />
          <mesh geometry={nodes.SmallDoor_OutsideWindowLight_0.geometry} material={materials.OutsideWindowLight} />
        </group>
        <group position={[70.96, 1219.193, 3.448]} rotation={[-Math.PI / 2, 0, 0]} scale={[5, 70, 137.5]}>
          <mesh geometry={nodes.BigDoor_WhiteWalls001_0.geometry} material={materials['WhiteWalls.001']} />
          <mesh geometry={nodes.BigDoor_OutsideWindowLight_0.geometry} material={materials.OutsideWindowLight} />
          <mesh geometry={nodes.BigDoor_DoorHandle_0.geometry} material={materials.DoorHandle} />
        </group>
        <mesh geometry={nodes.Frame_WhiteWalls001_0.geometry} material={materials['WhiteWalls.001']} position={[-5.531, 124.634, 3.345]} rotation={[-Math.PI / 2, 0, 0]} scale={[5, 100, 137.5]} />
      </group>
    </group>
  )
}

useGLTF.preload('/white_double_windowed_door/scene.gltf')
