/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/fire_escape_exit_doors/scene.gltf -o app/assets/3dmodel/FireEscapeDoor.jsx 
Author: blue man group (https://sketchfab.com/bloobloo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fire-escape-exit-doors-4ad9f395571a4dfaadce33dfeccc7a53
Title: Fire Escape / Exit Doors
*/
"üse client"

import React, {useEffect} from "react";
import { useGLTF, useTexture } from "@react-three/drei";


export function FireEscapeDoor(props) {
  const { nodes, materials } = useGLTF(
    "/models/fire_escape_exit_doors/scene.gltf"
  );
  const doorTexture = useTexture( "/models/fire_escape_exit_doors/textures/Metal_Guard.001_metallicRoughness.png")
   useEffect(() => {
    console.log(doorTexture.image)
      if (materials["316313476cfe2ddee7782e7855b64367"] && doorTexture?.image) {
        materials["316313476cfe2ddee7782e7855b64367"].map = doorTexture;
        materials["316313476cfe2ddee7782e7855b64367"].needsUpdate = true;
      }
    }, []);
  return (
    <group {...props} dispose={null}>
      <group position={[-0.14, 0.882, 0.064]}>
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.Handle_mech}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials["Metal_Guard.001"]}
        />
      </group>
      <group position={[-0.111, 1.123, 0.06]} scale={0.482}>
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials["Rear_Doors.001"]}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials["Material.139"]}
        />
      </group>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["316313476cfe2ddee7782e7855b64367"]}
        position={[-0.14, 1.417, -0.299]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.142}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.Chrome_Handle}
        position={[-0.14, 0.882, 0.064]}
      />
      <mesh
        geometry={nodes.Object_11.geometry}
        material={materials.Metal_Guard}
        position={[-0.138, 0.294, 0.045]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.104, 0.104, 0.104]}
      />
      <mesh
        geometry={nodes.Object_13.geometry}
        material={materials.c790c7f50dab9e8a5c5f82b94b61fbc8}
        position={[-0.14, 1.097, -0.299]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[-0.082, 0.082, 0.082]}
      />
    </group>
  );
}

useGLTF.preload("/scene.gltf");
