/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/door_metal_door_window/scene.gltf -o app/assets/3dmodel/MetalDoubleDoor.jsx 
Author: adventurer (https://sketchfab.com/ahmagh2e)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/door-metal-door-window-7mb-362754895ebe411bb027966bcf9a86a1
Title: Door Metal door window - 7MB
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function MetalDoubleDoor(props) {
  const { nodes, materials } = useGLTF('/door_metal_door_window/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-30.077, 3.691, 0]}>
          <mesh geometry={nodes.frame__0.geometry} material={materials['Scene_-_Root']} position={[30.077, -3.691, 0]} />
          <mesh geometry={nodes.L__0.geometry} material={materials['Scene_-_Root']} position={[-80.333, 0.36, 0.001]} rotation={[0, 0.436, 0]} />
          <mesh geometry={nodes.R__0.geometry} material={materials['Scene_-_Root']} position={[140.306, 0.466, 0]} rotation={[0, -0.893, 0]} />
        </group>
        <group position={[341.908, 3.691, 0]}>
          <mesh geometry={nodes.frame_2__0.geometry} material={materials['Scene_-_Root']} position={[0, -3.691, 0]} />
          <mesh geometry={nodes.L_2__0.geometry} material={materials['Scene_-_Root']} position={[-110.193, 0.574, 0]} />
          <mesh geometry={nodes.R_2__0.geometry} material={materials['Scene_-_Root']} position={[110.498, 0.574, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/door_metal_door_window/scene.gltf')
