/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/door/scene.gltf -o app/assets/3dmodel/NewDoor.jsx 
Author: Arnau Rocher Alcayde (https://sketchfab.com/ArnauRocherAlcayde)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/door-d6b9b84b78ae4462a6cf021b412085fe
Title: Door
*/
"use client";
import React, { useEffect } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { useAppStore } from "@/app/hooks/useAppStore";

export function NewDoor(props) {
  const { nodes, materials } = useGLTF("/models/door/scene.gltf");
  const doorTexture = useTexture("/Wood/Wood093_2K-JPG_Color.jpg");

  useEffect(() => {
    if (materials?.MAT_Door && doorTexture?.image) {
      materials.MAT_Door.map = doorTexture;
      materials.MAT_Door.needsUpdate = true;
    }
  }, []);

  // if (!nodes || !materials || !doorTexture?.image) return null;
  return (
    <group {...props} dispose={null}>
      <group scale={0.1}>
        <mesh
          geometry={nodes.Door_MAT_Door_0.geometry}
          material={materials.MAT_Door}
        />
        <mesh
          geometry={nodes.Parte_Pomo_MAT_Door_Handle_0.geometry}
          material={materials.MAT_Door_Handle}
        />
        <mesh
          geometry={nodes.Prame1_MAT_Prame_0.geometry}
          material={materials.MAT_Prame}
        />
        <mesh
          geometry={nodes.Maneta_2_MAT_Door_Handle_0.geometry}
          material={materials.MAT_Door_Handle}
        />
        <mesh
          geometry={nodes.Marco_Pomo_MAT_Door_Handle_0.geometry}
          material={materials.MAT_Door_Handle}
        />
        <mesh
          geometry={nodes.Maneta_1_MAT_Door_Handle_0.geometry}
          material={materials.MAT_Door_Handle}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/door/scene.gltf");
