/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/simple_double_door/scene.gltf -o app/assets/3dmodel/SimpleDoubleDoor.jsx 
Author: indoeditor7 (https://sketchfab.com/indoeditor7)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-double-door-2837dcca0e7b4bcd8d8944895671f0a2
Title: Simple Double Door
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function SimpleDoubleDoor(props) {
  const { nodes, materials } = useGLTF('/models/simple_double_door/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1}>
        <group position={[0.805, 0.14, 0]} rotation={[0, 0, -0.308]}>
          <mesh geometry={nodes.Panel001_Door_inside_0.geometry} material={materials.Door_inside} />
          <mesh geometry={nodes.Panel001_Door_outside_0.geometry} material={materials.Door_outside} />
        </group>
        <group position={[-0.805, 0.14, 0]} rotation={[0, 0, 0.707]}>
          <mesh geometry={nodes.Panel_Door_inside_0.geometry} material={materials.Door_inside} />
          <mesh geometry={nodes.Panel_Door_outside_0.geometry} material={materials.Door_outside} />
          <mesh geometry={nodes.Handle_Handle_inside_0.geometry} material={materials.Handle_inside} position={[0.735, 0, 1.003]} />
        </group>
        <mesh geometry={nodes.Door_Door_inside_0.geometry} material={materials.Door_inside} />
        <mesh geometry={nodes.Door_Door_outside_0.geometry} material={materials.Door_outside} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
